filebeat.inputs:
  - type: container
    enabled: true
    paths:
      - /var/lib/docker/containers/*/*.log
    stream: all
    processors:
      - add_fields:
          target: ""
          fields:
            app: movie-rating-service
            env: local

processors:
  - add_docker_metadata: ~
  - add_host_metadata: ~

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
setup.kibana:
  host: "http://kibana:5601"

logging.level: info
