spring:
  application:
    name: movie-rating-service
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    url: jdbc:h2:mem:mydb
    username: user
    password: user
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /api-docs.html