spring:
  application:
    name: movie-rating-service
  flyway:
    enabled: true
    locations: classpath:db/migration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie_rating
    username: movieuser
    password: moviepassword
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

springdoc:
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui.html

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,metrics,prometheus,heapdump
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
  info:
    env:
      enabled: true
    git.mode: full
    build.enabled: false
  metrics:
    enable:
      http.client.requests: true
      http.server.requests: true
      method.timed: true
    distribution:
      percentiles-histogram:
        http.client.requests: true
        http.server.requests: true
        method.timed: true
      percentiles:
        http.client.requests: 0.5,0.9,0.99
        http.server.requests: 0.5,0.9,0.99
        method.timed: 0.5,0.9,0.99
  prometheus:
    metrics:
      export:
        enabled: true

# get secret from secret-manager
app:
  jwt:
    secret: kB7sD9vN3xQ2mL8yF5zR1tU4oJ6pC0aEwH9iV2nY5qG7sX3bT1


