CREATE TABLE IF NOT EXISTS ROLES
(
    id                    BIGINT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name                  VARCHAR(255)   NOT NULL,
    created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PRIVILEGES
(
    id                    BIGINT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
    name                  VARCHAR(255)   NOT NULL,
    created_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS USERS_ROLES
(
    user_id     BIGINT       NOT NULL,
    role_id     BIGINT       NOT NULL,
    created_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_users_roles_user
    FOREIGN KEY (user_id) REFERENCES USERS (id) ON DELETE CASCADE,
    CONSTRAINT fk_users_roles_role
    FOREIGN KEY (role_id) REFERENCES ROLES (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ROLES_PRIVILEGES
(
    role_id        BIGINT       NOT NULL,
    privilege_id   BIGINT       NOT NULL,
    created_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP    DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, privilege_id),
    CONSTRAINT fk_roles_privileges_role
    FOREIGN KEY (role_id) REFERENCES ROLES (id) ON DELETE CASCADE,
    CONSTRAINT fk_roles_privileges_priv
    FOREIGN KEY (privilege_id) REFERENCES PRIVILEGES (id) ON DELETE CASCADE
);

