INSERT INTO MOVIES (name, rating_count, average_rating) VALUES
                                                            ('The Shawshank Redemption', 2, 10.0000),
                                                            ('The Godfather', 2, 9.5000),
                                                            ('The Dark Knight', 1, 9.0000),
                                                            ('Pulp Fiction', 2, 8.5000),
                                                            ('Forrest Gump', 1, 8.0000),
                                                            ('Inception', 2, 9.0000),
                                                            ('Fight Club', 1, 8.0000),
                                                            ('The Matrix', 2, 9.5000),
                                                            ('Goodfellas', 2, 9.0000),
                                                            ('The Lord of the Rings: The Fellowship of the Ring', 1, 9.0000),
                                                            ('Star Wars: Episode V - The Empire Strikes Back', 2, 9.5000),
                                                            ('Interstellar', 1, 9.0000),
                                                            ('The Green Mile', 2, 8.5000),
                                                            ('Gladiator', 1, 8.0000),
                                                            ('The Lion King', 2, 9.0000),
                                                            ('Saving Private Ryan', 1, 9.0000);